// https://fontawesome.com/icons
export const IconTypes = {
  add: 'fa fa-plus-circle',
  link: 'fa fa-link',
  user: 'fa fa-user',
  save: 'fa fa-save',
  create: 'fa fa-plus',
  revert: 'fa fa-history',
  delete: 'fa fa-trash',
  edit: 'fa fa-edit',
  copy: 'fa fa-copy',
  details: 'fa fa-info',
  tasks: 'fa fa-tasks',
  list: 'fa fa-list',
  search: 'flaticon-search-1',
  attachments: 'fa fa-paperclip',
  insurance: 'fa fa-gavel',
  options: 'fa fa-book',
  bond: 'fa fa-file',
  charges: 'fa fa-dollar-sign',
  sales: 'fa fa-shopping-cart',
  id: 'fa fa-hashtag',
  date: 'fa fa-calendar-alt',
  bell: 'fa fa-bell',
  circle: 'fa fa-circle',
  circleInfo: 'fa-solid fa-circle-info',
  halfCircle: 'fas fa-adjust',
  tickCircle: 'fa fa-check-circle',
  tickEmptyCircle: 'far fa-circle',
  tick: 'fa fa-check',
  calendarTick: 'fa fa-calendar-check',
  cross: 'fa fa-times',
  pause: 'fa fa-pause',
  hourglass: 'fa fa-hourglass',
  navToStart: 'fa fa-angle-double-left',
  navPrevious: 'fa fa-angle-left',
  navForward: 'fa fa-angle-right',
  navDown: 'fa fa-angle-down',
  navToEnd: 'fa fa-angle-double-right',
  map: 'fa fa-map-marked',
  more: 'fa fa-ellipsis-v',
  bars: 'fa fa-bars',
  refresh: 'fa fa-sync',
  play: 'fa fa-play',
  spinner: 'fa fa-spin fa-spinner',
  arrowDown: 'fa fa-angle-down',
  arrowUp: 'fa fa-angle-up',
  users: 'fa fa-users',
  documents: 'fa fa-folder',
  wordFile: 'fa fa-file-word',
  excelFile: 'fa fa-file-excel',
  imageFile: 'fa fa-file-image',
  fallbackFile: 'fa fa-file-alt',
  upload: 'fa fa-upload',
  download: 'fa fa-download',
  warning: 'fa fa-exclamation-triangle',
  question: 'fa fa-question',
  exclamation: 'fa fa-exclamation-circle',
  projectDiagram: 'fa fa-project-diagram',
  file: 'fa fa-file',
  history: 'fa fa-history',
  comment: 'fa fa-comment',
  levelDown: 'fa fa-level-down-alt',
  levelUp: 'fa fa-level-up-alt',
  bold: 'fa fa-bold',
  italic: 'fa fa-italic',
  underline: 'fa fa-underline',
  quotes: 'fa fa-quote-right',
  listOrdered: 'fa fa-list-ol',
  listUnordered: 'fa fa-list-ul',
  businessProcess: 'flaticon-pie-chart',
  property: 'flaticon-buildings',
  lease: 'fa fa-book',
  drag: 'fa fa-grip-horizontal',
  alarm: 'flaticon-alarm',
  expand: 'fa fa-expand',
  compress: 'fa fa-compress',
  caretLeft: 'fa fa-caret-left',
  calendar: 'fa fa-calendar',
  wrench: 'fa fa-wrench',
};